pipeline {
    agent any {
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'master',
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/Gracydinma/alx-backend-python'
            }
        }
        stage('Install Dependencies') {
            steps {
                // Install pytest
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install pytest
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest --junitxml=reports/test-results.xml
                '''
            }
        }

        stage('Publish Report') {
            steps {
                junit 'reports/test-results.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    app = docker.build("gracedinma/messaging_app:latest")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.io/v1', 'docker-credentials') {
                    // pushing docker image
                        app.push()
                    }
                }
            }
        }
    }
}